### ISSUE TITLE
MacOS - Analysis of Result windows

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#12]
Graph windows in AoR are stack in the foreground, eventually covering the main AoR window. Iconifying them does not work, as all of the disappear in a single icon together with the AoR window. On small screens it is a nightmare.

**Comment by MCP1** [comment]
I cannot reproduce this problem in a regular AoR session, please tell me the steps to reproduce. 

This is a known limitation **only** when using AoR during a **debug** session in macOS. If this is your case, as you may remember, this is the best compromise I could find, because of the coarse Tk/Aqua grabbing granularity. The (worse) alternative was going back to the "all windows floating" scheme, where the user usually got lost with non-operational but still-available windows. A proper fix would require a major change on how LSD handles windows inputs, allowing really independent windows. This limitation doesn't affect Windows or Linux.

**Comment by MCP1** [comment]
Strange. Cannot reproduce it. Could you tell me the exact steps, from a model in the Examples, to reproduce the problem?

Look at the attached image: AoR at the foreground over 3 different plot windows (time series, gnuplot and histogram). Also High Sierra here. All installed fresh, no changes from repo.

![captura de tela 2018-10-06 as 15 01 36](https://user-images.githubusercontent.com/2797821/46574404-03fdf180-c979-11e8-84b9-b68ef6e2a610.png)

**Comment by marcov64** [comment]
Marcelo,
you were right, when you mentioned the debug mode I thought of executing a simulation run in gdb. It is rather the LSD debug mode, using AoR when simulation is not completed, you were referring to. Annoying (and mysterious) as it is the issue I think it is tolerable until we find a fix for the windows problem.
I close the issue here.

Ciao
Marco
