### ISSUE TITLE
Option to access models in LSD external Work folder

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#19]
If it was possible to set/access external Work folders this would be great. Because git in git is not an option, one has to copy and past currently if one is using a git repository for the models AND has cloned the repo of LSD to get updates. (SVN in git is possible, though)

**Comment by MCP1** [comment]
It was evaluated to implement it before but it may be tricky to compile code anywhere in the file system because of the references for compiler and the make tool, which by the way is somewhat different in the 3 platforms. The benefits doesn't seem to compensate the effort and the problems. No plan to implement this.

It's not correct that you can't have git in git. I have both LSD and most of my models in the Work subfolder linked to different git repos. Never had to copy/paste folders. If you check LSD .gitignore file, the Work subfolder is excluded from git analysis, so you can do anything here that you can do anywhere else in the system.
