### ISSUE TITLE
EQ_USER_VARS 

### ISSUE THREAD

**Issue by FrederikSchaff** [marcov64/Lsd#37]
Currently EQ_USER_VARS  is included in each single EQUATION (within EQ_BEGIN). Therefore, the variables are not global as they should be. I suggest to move the calling of the macro from EQ_BEGIN (which is called both, in MODELBEGIN ad EQUATION) to 'only' MODELBEGIN, directly after EQ_BEGIN.

**Comment by MCP1** [comment]
Thanks for the heads-up Frederik. EQ_USER_VARS is indeed working as designed. The problem was on the inadequate documentation about its usage, which is now corrected.

Global C++ variables have always been possible in LSD, simply declare them before MODELBEGIN in your equation files. As the name indicates, EQ_USER_VARS exists to simplify the creation of user-level temporary variables and other definitions for usage in equations, probably many, reducing the need for repeating the same definitions over and over.
