### ISSUE TITLE
Case sensitive search in LMM

### ISSUE THREAD

**Issue by marcov64** [marcov64/Lsd#43]
By default LMM assumes the search in the text (Find) as case sensitive. It makes no sense, because it is very rare to require this sensitivity and one has to waste time to use the correct capitalisation. Moreover, switching off the option for case sensitivity is nor remembered in the next search.
I'd force as default the lack of sensitivity, or even to remove the option altogether. At least, I'd like to record the option for the next search.

**Comment by MCP1** [comment]
Hi Marco.
Long time ago I changed the default to case sensitive because of the confusion the previous default used to bring to students (particularly when locating their misusage of case sensitivity). I would keep it this way if possible but I agree changing the options must be persistent at least for the session. 
I implemented a commit to do so, please check. Please note I didn't recompile Mac LMM app (will do when consolidating a new beta installer). For now, please go to the LSD/src folder in terminal and use "make -f makefile.mac" after pulling the changes from github.

**Comment by marcov64** [comment]
Ok, I understand. It is a typical case of novice vs expert users, for the former it is better case sensitive for the latter the opposite. The persistency seems to me the best compromise. Thanx!
